{
 "title": "Logs Explorer",
 "tags": [
  "logs",
  "loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Log Volume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Log Volume by Level",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({job=\"flask-app\"} | json | level != \"\" [1m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  { "title": "Error Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Error & Warning Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"flask-app\"} | json | level =~ \"ERROR|CRITICAL|WARNING\""
    }
   ]
  },
  { "title": "All Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{job=\"flask-app\", environment=\"prod\"}"
    }
   ]
  },
  { "title": "Chaos & Component Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Chaos Monkey Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{job=\"flask-app\"} |= \"chaos\" "
    }
   ]
  },
  {
   "title": "Alert System Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "{job=\"flask-app\"} | json | component = \"alerts\""
    }
   ]
  }
 ]
}