global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "flask-prod-nyc"
    metrics_path: "/prom-metrics"
    scheme: https
    static_configs:
      - targets:
          - pe-hackathon-muy5v.ondigitalocean.app
        labels:
          region: "nyc"
          environment: "prod"

  - job_name: "flask-prod-sfo"
    metrics_path: "/prom-metrics"
    scheme: https
    static_configs:
      - targets:
          - pe-hackathon-prod-sfo-wkpqr.ondigitalocean.app
        labels:
          region: "sfo"
          environment: "prod"

  - job_name: "flask-staging"
    metrics_path: "/prom-metrics"
    scheme: https
    static_configs:
      - targets:
          - pe-hackathon-staging-f28oj.ondigitalocean.app
        labels:
          region: "nyc"
          environment: "staging"

