global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "flask-prod"
    metrics_path: "/prom-metrics"
    scheme: https
    static_configs:
      - targets:
          - PLACEHOLDER_APP_URL
        labels:
          environment: "prod"
