global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "flask-prod"
    metrics_path: "/prom-metrics"
    scheme: http
    static_configs:
      - targets:
          - 104.248.125.189
        labels:
          environment: "prod"

  - job_name: "flask-staging"
    metrics_path: "/prom-metrics"
    scheme: http
    static_configs:
      - targets:
          - 137.184.196.25
        labels:
          environment: "staging"
